agent.go
agent_test.go

* moved enabled to int from bool
* updated tests to include the enabled flag
* [bug][2] raised terraform-provider-thousandeyes fails to marshal into struct due to field being a int not bool. 
* [API Docs][1]
* [Terraform provider bug][2]
[1]: https://developer.thousandeyes.com/v6/tests/
[2]: https://github.com/william20111/terraform-provider-thousandeyes/issues/4

fix(agent): tests have enabled field as int not bool

---

bgp_monitor_test.go
bgp_test.go
ftp_server.go
ftp_server_test.go

* ftp-server test support
* Get all test types supported before #32 starts

feat(ftp-server): add support for ftp server test

---

agent_agent.go

* This accepts `0` so `omitempty` ignores this field when you try to set dscp
* When creating AgentAgent tests it cause havoc ignoring this field william20111/terraform-provider-thousandeyes#14

fix(dscpId): remove the omit from marshall on dscpId

---

.goreleaser.yml

* windows included in default builds
* windows users now included in CI builds

fix(goreleaser): include windows builds

---

client.go
client_test.go
command/tectl/cmd/agents.go
command/tectl/cmd/tests.go

This adds support for sending the account group ID to differentiate between multiple accounts accessible by a single user token.

feat(account-groups) Support sending account group

---

client.go
client_test.go

* Keep it stupid simple and provide an optional rate limit interface on the client to delay calls and avoid any rate limiting. This can be then implemented by the consumer rather than any decisions made by library for the consumer
* BREAKING CHANGE: changes the client options to config struct

feat(client): client rate limiter option

---

client.go
client_test.go

Based on prior conversation on [the previous PR](https://github.com/william20111/go-thousandeyes/pull/64) indicating being open to the possibilty, I am re-submitting this branch for reconsideration.
The purpose of this is not to enforce client-side rate limiting, but to comply with rate limiting when the server reports that it is being imposed (which is always when ThousandEyes is operating correctly).  Rate limiting is enforced on an org-wide basis by ThousandEyes, so a single client's voluntary rate limiting would not necessarily prevent overrunning a rate limit.
An additional change is included in this submission to handle inconsistent response formation from ThousandEyes.

Rate limiting

---

integration.go
integration_test.go

Support for reading integrations for alert rules will enable terraform-provider-thousandeyes to utilize alert rules as a resource rather than a data source.

Add support for reading alert integrations

---

http_server.go
page_load.go
web_transaction.go

customHeaders field in ThousandEyes API is an object rather than a
string.  There is an undocumented customHeadersForm field which is an
escaped JSON string which might suffice for issues integrating with
this format.

fix: Correct type for customHeaders field

---

README.md

Adding Acknowledgements section to README to thank William Fleming, John Dyer, and Joshua Blanchard.  Our GH org policy doesn't allow us to keep external collaborators on a repo and I wanted to publicly thank these three folks for their work on this project and the related Terraform provider.
Note: I also updated references in the header images for the README to point to the new repo location.  This may have broken some services which require registration.

Adding Acknowledgements to README

---

command/tectl/cmd/agents.go
command/tectl/cmd/tests.go

I inadvertently broke `tectl` compilation with #90, #91 and #92. This contribution fixes it.

fix(tectl): use pointers for accesing fields

---

README.md
command/tectl/cmd/agents.go
command/tectl/cmd/root.go
command/tectl/cmd/tests.go
command/tectl/main.go
go.mod

This is required when releasing [breaking changes](https://go.dev/doc/modules/release-workflow#breaking).

chore: bump module path to v2

---

README.md
command/tectl/cmd/agents.go
command/tectl/cmd/root.go
command/tectl/cmd/tests.go
command/tectl/main.go
go.mod

In order to better identify this project as being an SDK, we will rename it to `thousandeyes-sdk-go`. This will also better set us up for adding additional SDKs in other languages.

chore!: rename project to thousandeyes-sdk-go

---

alerts.go

Setting `NotifyOnClear` and `Default` as booleans. Rationale for this change is in #91.

refactor(alerts)!: notifyOnClear and default as booleans

---

client.go
client_test.go

Defaults to "ThousandEyes Go SDK"
Tests run successfully:
```
go vet ./... && echo && go test ./...
ok  	github.com/thousandeyes/thousandeyes-sdk-go/v2	1.161s
```
Tested in the terraform provider locally too:
```
go vet ./... && echo && go test ./...
?   	github.com/thousandeyes/terraform-provider-thousandeyes	[no test files]
ok  	github.com/thousandeyes/terraform-provider-thousandeyes/thousandeyes	0.422s
```
Terraform Plan with provider development override also worked well:
```
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - thousandeyes/thousandeyes in /Users/pedrorg/go/bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the …
```

feat: adds configurable user-agent header to HTTP client

---

alert_test.go
alerts.go

Added necessary structs to support third party notifications (via slack, pagerduty, etc) in alerts. This feature is lacking in your new-ish terraform provider and would be of great use. I used your API docs as reference: https://developer.thousandeyes.com/v6/alerts/#/alert-rule-create
I suppose a follow-up pull request on your provider using a newer version of this SDK will need to happen later. Let me know if anything else is needed and if I can facilitate any work to speed things up.
Thanks for your work. 🙇🏼

Implement third party notification support within alerts

---

agent.go
agent_agent.go
bgp.go
client.go
client_test.go
dns_server.go
dns_trace.go
group_label.go
http_server.go
page_load.go
sip_server.go
voice.go
web_transaction.go

* Also fixes one of the unit tests which was actually not running
* I ran `go fmt` which is what fixed the spacing in those comments
This is useful to allow us to use terraform with our staging environments. 
Tests are clean:
```
go vet ./... && echo && go test ./...
ok  	github.com/thousandeyes/thousandeyes-sdk-go/v2	1.386s
```
Tested locally without overriding:
```
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - thousandeyes/thousandeyes in /Users/pedrorg/go/bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
thousandeyes_alert_rule.test_alert_rule: Refreshing state... …
```

feat: allows overriding the API Endpoint

---

group_label.go

When all agents or tests were removed from a label/group the client was marshalling the absence of those fields to null. The ThousandEyes API ignored the null value and didn't actually make any changes to the label/group. But from terraform's perspective the agents/tests had been removed (from the state). By passing an empty array, the ThousandEyes API removes the agents/tests sucessfully from the label.
Before change with debug logging enabled:
```
thousandeyes_label.pedro-label-agents: Modifying... [id=X]
2023-01-16T18:31:49.816Z [INFO]  Starting apply for thousandeyes_label.pedro-label-agents
2023-01-16T18:31:49.817Z [INFO]  provider.terraform-provider-thousandeyes: 2023/01/16 18:31:49 [INFO] Updating ThousandEyes Label 582876: timestamp=2023-01-16T18:31:49.817Z …
```

fix: ensures an empty array is marshalled rather than null in labels

---

alerts.go

Seems like this change was [previously made](https://github.com/thousandeyes/thousandeyes-sdk-go/pull/114) but was never merged into the main branch, so I'm creating it again.

feat: add severity property to alert rule

---

alert_test.go
alerts.go

This aims to ultimately support using webhooks for integrations within the ThousandEyes terraform provider. 
Currently, if you create a custom webhook integration (for example, Microsoft Teams), you can't use it to create/update alert rules with webhook notifications (using an integration data source in terraform).
I think there just needs to be an additional struct, if this is wrong please let me know. 
Any feedback would be appreciated!

Adding notification webhook structure

---

alerts.go

Adds the missing Tests field in the alert rule read operation.
Also changes the TestIds to int64 to match the Test.Id schema.

fix: alert rule read add Tests response object
